/*AUTHOR: HUSSEIN AHMED TEJAN
 * This frame is required to enable the mechanic to fill in the customer details to book an appointment for their vehicle to be service based on the Mileage Usage.
 */
package gui;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import maintenancebookings.Usagebased;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;

/**
 *
 * @author ht304
 */
    public                                              class                   UsageBasedServiceBooking            extends javax.swing.JFrame {

                                                                                Usagebased                          usbController;
    private                                                                     int                                 vID;
    private                                                                     String                              bType;
    private                                                                     int                                 currentMileage;
                                                                                Connection                          conn = null;
                                                                                ResultSet                           rs = null;
                                                                                PreparedStatement                   pst = null;

    private                                                                     int                                 bayNum;
    private                                                                     int                                 prevMileage;

                                                                                OptionBasedSchedule                 showPreviouslyBookedServices;
                                                                                Appointment                         bookingApp;

    public         UsageBasedServiceBooking(Appointment appBooking, OptionBasedSchedule showBookedServices, Usagebased controllerUsb) {
        initComponents();
                                                                                bookingApp =                        appBooking;
                                                                                showPreviouslyBookedServices =      showBookedServices;
                                                                                usbController =                     controllerUsb;

        try {
            UIManager.setLookAndFeel(UIManager.getSystemLookAndFeelClassName());
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(UsageBasedServiceBooking.class.getName()).log(Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            Logger.getLogger(UsageBasedServiceBooking.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            Logger.getLogger(UsageBasedServiceBooking.class.getName()).log(Level.SEVERE, null, ex);
        } catch (UnsupportedLookAndFeelException ex) {
            Logger.getLogger(UsageBasedServiceBooking.class.getName()).log(Level.SEVERE, null, ex);
        }

    }

    private                                         void                            setVehicleID() {
        vIDUsb.setText("" + vID);

    }

    private                                         void                            setBookingType() {
        bTypeUsb.setText(bType);
    }

    private                                         void                            setcurrentMileage() {
        usbPresentMileage.setText("" + currentMileage);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        BookingType = new javax.swing.JLabel();
        bTypeUsb = new javax.swing.JTextField();
        Mileage = new javax.swing.JLabel();
        usbPresentMileage = new javax.swing.JTextField();
        vehicleID = new javax.swing.JLabel();
        vIDUsb = new javax.swing.JTextField();
        serviceSubmit = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        bayNo = new javax.swing.JComboBox();
        previousbookedServices = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        BookingType.setText("Booking Type:");

        bTypeUsb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bTypeUsbActionPerformed(evt);
            }
        });

        Mileage.setText("Mileage:");

        usbPresentMileage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                usbPresentMileageActionPerformed(evt);
            }
        });

        vehicleID.setText("VehicleID:");

        vIDUsb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                vIDUsbActionPerformed(evt);
            }
        });

        serviceSubmit.setText("SUBMIT");
        serviceSubmit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                serviceSubmitActionPerformed(evt);
            }
        });

        jLabel1.setText("Bay No:");

        bayNo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "1", "2", "3", "4", "5", "6" }));
        bayNo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bayNoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(vehicleID)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(vIDUsb, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(BookingType)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(bTypeUsb, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel1)
                            .addComponent(Mileage))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(usbPresentMileage, javax.swing.GroupLayout.DEFAULT_SIZE, 133, Short.MAX_VALUE)
                            .addComponent(bayNo, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addGap(115, 115, 115))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(72, 72, 72)
                .addComponent(serviceSubmit, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(vehicleID)
                    .addComponent(vIDUsb, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(17, 17, 17)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BookingType)
                    .addComponent(bTypeUsb))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Mileage)
                    .addComponent(usbPresentMileage, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(bayNo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addComponent(serviceSubmit, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(148, 148, 148))
        );

        previousbookedServices.setText("View Previously Booked Services");
        previousbookedServices.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                previousbookedServicesActionPerformed(evt);
            }
        });

        jLabel2.setText("Register a new Service");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(47, 47, 47)
                        .addComponent(previousbookedServices))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 317, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(113, 113, 113)
                        .addComponent(jLabel2)))
                .addContainerGap(27, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(previousbookedServices)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 335, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 20, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bTypeUsbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bTypeUsbActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bTypeUsbActionPerformed

    private void usbPresentMileageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_usbPresentMileageActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_usbPresentMileageActionPerformed

    private void vIDUsbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_vIDUsbActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_vIDUsbActionPerformed

    private void serviceSubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_serviceSubmitActionPerformed

        try {
              conn = javaconnect.ConnecrDb();
            Statement stat = conn.createStatement();
            //Displays information from Database into jTable: UsageBasedService in OptionBasedSchedule
            String sql2 ="select * from UsageBasedService";
            rs = stat.executeQuery(sql2);
            int count = 0;
            int itemNum = 0;

            while (rs.next()) {
                if (vID == rs.getInt("vehicleID")) {
                    count = count + 1;
                }

            }
            while (rs.next()) {
                if (vID == rs.getInt("vehicleID")) {
                    itemNum = itemNum + 1;

                    if (count == itemNum) {
                        prevMileage = rs.getInt("currentVehicleMileage");
                        break;
                    }

                }

            }

            usbController.setVehicleID(vID);
            usbController.setBookingType(bType);
            usbController.setMiles(0);
            usbController.setDifference(prevMileage);
          
            usbController.workoutDifference(usbController.getDifference(), minimumMil, maximumMil);

            showPreviouslyBookedServices.setVisible(false);
            this.setVisible(false);

            try {
            //Inserts the data entered in the UsageBasedService form into the UsageBasedService table within the Database.

                String sql = "INSERT INTO UsageBasedService "
                        + "(vehicleID, currentVehicleMileage, BookingType, bayNumber)"
                        + "VALUES (?,?,?,?)";
                pst = conn.prepareStatement(sql);
                pst.setString(1, vIDUsb.getText());
                pst.setString(2, usbPresentMileage.getText());
                pst.setString(3, bTypeUsb.getText());
                pst.setInt(4, bayNum);

                pst.executeUpdate();
            } catch (Exception ne) {
                System.out.println("Cannot Perform Query");
                ne.printStackTrace();

            }

        } catch (SQLException ex) {
            Logger.getLogger(UsageBasedServiceBooking.class.getName()).log(Level.SEVERE, null, ex);
        }


    }//GEN-LAST:event_serviceSubmitActionPerformed
    //maxMileage
    public static final int maximumMil = 120000;
    //minMileage
    public static final int minimumMil = 10000;

    private void previousbookedServicesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_previousbookedServicesActionPerformed

        showPreviouslyBookedServices.setVisible(true);

        this.setVisible(false);
    }//GEN-LAST:event_previousbookedServicesActionPerformed

    private void bayNoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bayNoActionPerformed

        bayNum = Integer.parseInt(bayNo.getSelectedItem().toString());

        if (bayNo.equals(bookingApp.processSchedule.getBayNumber())) {
            System.out.println(bayNum);
        }
    }//GEN-LAST:event_bayNoActionPerformed

    /**
     * @param args the command line arguments
     */
            public                                                  static                      void                main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;

                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UsageBasedServiceBooking.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UsageBasedServiceBooking.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UsageBasedServiceBooking.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UsageBasedServiceBooking.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public                                                                              void                run() {

            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel BookingType;
    private javax.swing.JLabel Mileage;
    private javax.swing.JTextField bTypeUsb;
    private javax.swing.JComboBox bayNo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JButton previousbookedServices;
    private javax.swing.JButton serviceSubmit;
    private javax.swing.JTextField usbPresentMileage;
    private javax.swing.JTextField vIDUsb;
    private javax.swing.JLabel vehicleID;
    // End of variables declaration//GEN-END:variables
}
