/*
* To change this license header, choose License Headers in Project Properties.
* To change this template file, choose Tools | Templates
* and open the template in the editor.
*/

package partsproject;

/**
 * @author jpma3
 */

/* import the package from java library*/
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.Date;
import javax.swing.JOptionPane;
import net.proteanit.sql.DbUtils;

public class newRepair extends javax.swing.JFrame {
    // initialize variables for database connection
    Connection connect = null;
    ResultSet res = null;
    PreparedStatement stat = null;
    
    /**
     * Creates new form newRepair
     */
    
    public newRepair() {
        connect = dbConnect.databaseconnect(); // connect to the sqllite database
        initComponents();
        updateRepair(); //update the newRepair table
    }
    
    private void clearRepair(){
        /* set null value to all textfields in order to clear the text*/
        rIDTextField.setText(null);
        vecTextField.setText(null);
        mecIDTextField.setText(null);
        pIDTextField.setText(null);
        pNamTextField.setText(null);
        iDateTextField.setText(null);
        wDateTextField.setText(null);
    }
    
    private void checkStock(){
        String value = pIDTextField.getText();
        String query3 = "select * from Parts where PartID='"+value+"' ";
        
        String message = "Do you want to order this part " +value+" from suppliers ?";
        String title = "Part " +value+ " is not in stock";
        try{
            stat = (PreparedStatement) connect.prepareStatement(query3);
            res = stat.executeQuery();
            if(res.next())
            {
                
                String rem = res.getString("partsRemaining");
                if (rem.equalsIgnoreCase("0"))
                {
                    
                    int response = JOptionPane.showConfirmDialog(null, message, title, JOptionPane.YES_NO_OPTION);
                    if (response == JOptionPane.YES_OPTION) {
                        ordersGui order = new ordersGui();
                        order.setVisible(true);
                        setVisible(false);
                        
                    }
                    else{
                        pIDTextField.setText(null);}
                    
                     }
            }
            
            stat.close();
            res.close();
        }
        catch(Exception ex){
            JOptionPane.showMessageDialog(null, ex);
            
        }
    }
    private void upPart(){
        try {
            String id =pIDTextField.getText();
            String query = "update Parts set partsRemaining = partsRemaining-1 where PartID='"+id+"'";
            stat =  (PreparedStatement) connect.prepareStatement(query);
            stat.execute();
            stat.close();
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null,ex);
        }
    }
    
    private void updateRepair(){
        try {
            String query = "select RepairsID,mechanicID,vehicleID,PartID,partName,dateInstalled,dateWarranty from vehicleRepairs";
            stat =  (PreparedStatement) connect.prepareStatement(query);
            res = stat.executeQuery();
            repTable.setModel(DbUtils.resultSetToTableModel(res));
            res.close();
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null,ex);
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        rIDTextField = new javax.swing.JTextField();
        mecIDTextField = new javax.swing.JTextField();
        vecTextField = new javax.swing.JTextField();
        pIDTextField = new javax.swing.JTextField();
        pNamTextField = new javax.swing.JTextField();
        addRepButton = new javax.swing.JButton();
        clrButton = new javax.swing.JButton();
        updateButton = new javax.swing.JButton();
        iDateTextField = new javax.swing.JFormattedTextField();
        wDateTextField = new javax.swing.JFormattedTextField();
        jPanel2 = new javax.swing.JPanel();
        delAllButton = new javax.swing.JButton();
        delRepButton = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        repTable = new javax.swing.JTable();
        menuPanel = new javax.swing.JPanel();
        orderButton = new javax.swing.JButton();
        trackButton = new javax.swing.JButton();
        repGUIButton = new javax.swing.JButton();
        listButton = new javax.swing.JButton();
        tpsMenuButton = new javax.swing.JButton();
        parMenButton = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "New Repair", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.BELOW_TOP, new java.awt.Font("Lucida Grande", 1, 18))); // NOI18N

        jLabel1.setText("Repair ID");

        jLabel2.setText("Mechanic ID");

        jLabel3.setText("Vehicle ID");

        jLabel4.setText("Part ID");

        jLabel5.setText("Part Name");

        jLabel6.setText("Installed Date");

        jLabel7.setText("Warranty Date");

        rIDTextField.setEditable(false);
        rIDTextField.setText("ID");
        rIDTextField.setEnabled(false);

        mecIDTextField.setText("ID ");

        vecTextField.setText("ID");

        pIDTextField.setText("ID");

        pNamTextField.setText("Name");
        pNamTextField.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pNamTextFieldMouseClicked(evt);
            }
        });

        addRepButton.setText("Add");
        addRepButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addRepButtonActionPerformed(evt);
            }
        });

        clrButton.setText("Clear");
        clrButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clrButtonActionPerformed(evt);
            }
        });

        updateButton.setText("Update");
        updateButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateButtonActionPerformed(evt);
            }
        });

        iDateTextField.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter(new java.text.SimpleDateFormat("dd/MM/yyyy"))));
        iDateTextField.setText("dd/mm/yyyy");

        wDateTextField.setEditable(false);
        wDateTextField.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter(new java.text.SimpleDateFormat("dd/MM/yyyy"))));
        wDateTextField.setText("dd/mm/yyyy");
        wDateTextField.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                wDateTextFieldMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addComponent(addRepButton, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(clrButton, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(updateButton)
                        .addGap(46, 46, 46))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(wDateTextField)
                            .addComponent(iDateTextField)
                            .addComponent(pNamTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 149, Short.MAX_VALUE)
                            .addComponent(pIDTextField)
                            .addComponent(vecTextField)
                            .addComponent(mecIDTextField)
                            .addComponent(rIDTextField))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(rIDTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(mecIDTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(vecTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(pIDTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(pNamTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(iDateTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(wDateTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addRepButton)
                    .addComponent(clrButton)
                    .addComponent(updateButton))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createCompoundBorder());

        delAllButton.setText("Delete All");
        delAllButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                delAllButtonActionPerformed(evt);
            }
        });

        delRepButton.setText("Delete");
        delRepButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                delRepButtonActionPerformed(evt);
            }
        });

        repTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        repTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                repTableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(repTable);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 503, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(delRepButton, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(delAllButton)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(delRepButton)
                    .addComponent(delAllButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 255, Short.MAX_VALUE)
                .addContainerGap())
        );

        menuPanel.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        orderButton.setText("Orders");
        orderButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                orderButtonActionPerformed(evt);
            }
        });

        trackButton.setText("Track");
        trackButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                trackButtonActionPerformed(evt);
            }
        });

        repGUIButton.setText("New Repair");
        repGUIButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                repGUIButtonActionPerformed(evt);
            }
        });

        listButton.setText("Summary List");
        listButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                listButtonActionPerformed(evt);
            }
        });

        tpsMenuButton.setText("Third Party Suppliers");
        tpsMenuButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tpsMenuButtonActionPerformed(evt);
            }
        });

        parMenButton.setText("Parts");
        parMenButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                parMenButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout menuPanelLayout = new javax.swing.GroupLayout(menuPanel);
        menuPanel.setLayout(menuPanelLayout);
        menuPanelLayout.setHorizontalGroup(
            menuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(menuPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(menuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(menuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(orderButton, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(trackButton, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(repGUIButton, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(listButton, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(tpsMenuButton, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(parMenButton, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        menuPanelLayout.setVerticalGroup(
            menuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(menuPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(parMenButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(orderButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(trackButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(repGUIButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(listButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tpsMenuButton)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Vehicle Repairs", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.BELOW_TOP, new java.awt.Font("Lucida Grande", 0, 24))); // NOI18N

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(menuPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 337, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addComponent(menuPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void addRepButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addRepButtonActionPerformed
        String message = " Are you sure want to add the data?";
        String title = "Add new repair";
        int reply = JOptionPane.showConfirmDialog(null, message, title, JOptionPane.YES_NO_OPTION);
        if (reply == JOptionPane.YES_OPTION) {
            String query = "insert into vehicleRepairs (RepairsID,mechanicID,vehicleID,PartID,partName,dateInstalled,dateWarranty) values (?,?,?,?,?,?,?) ";
            try{
                stat =  (PreparedStatement) connect.prepareStatement(query);
                stat.setString(2,mecIDTextField.getText());
                stat.setString(3,vecTextField.getText());
                stat.setString(4,pIDTextField.getText());
                stat.setString(5,pNamTextField.getText());
                stat.setString(6,iDateTextField.getText());
                stat.setString(7,wDateTextField.getText());
                stat.execute();
                JOptionPane.showMessageDialog(null,"Data added succesfully");
                stat.close();
            } catch (Exception ex) {
                JOptionPane.showMessageDialog(null,"");
            }
            updateRepair();
            upPart();
            clearRepair();
        }
    }//GEN-LAST:event_addRepButtonActionPerformed

    private void clrButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clrButtonActionPerformed
        String message = " Are you sure want to clear the data?";
        String title = "Clear Data";
        int reply = JOptionPane.showConfirmDialog(null, message, title, JOptionPane.YES_NO_OPTION);
        if (reply == JOptionPane.YES_OPTION) {
            clearRepair();
        }
    }//GEN-LAST:event_clrButtonActionPerformed

    private void repTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_repTableMouseClicked
        try{
            int row = repTable.getSelectedRow();
            String repTable_click = (repTable.getModel().getValueAt(row, 0).toString());
            String query = "select * from vehicleRepairs where RepairsID ='"+repTable_click+" ' ";
            stat =  (PreparedStatement) connect.prepareStatement(query);
            res = stat.executeQuery();
            if (res.next())
            {
                String repID=res.getString("RepairsID");
                rIDTextField.setText(repID);
                String mecID=res.getString("mechanicID");
                mecIDTextField.setText(mecID);
                String addVec=res.getString("vehicleID");
                vecTextField.setText(addVec);
                String addID=res.getString("PartID");
                pIDTextField.setText(addID);
                String addNam=res.getString("partName");
                pNamTextField.setText(addNam);
                String addDat=res.getString("dateInstalled");
                iDateTextField.setText(addDat);
                String addWDate=res.getString("dateWarranty");
                wDateTextField.setText(addWDate);
            }
            stat.close();
            res.close();
        }
        catch(Exception ex){
            JOptionPane.showMessageDialog(null, ex);
        }
        updateRepair(); //Update the table
    }//GEN-LAST:event_repTableMouseClicked

    private void delAllButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_delAllButtonActionPerformed
        String message = " Are you sure want to delete all data?";
        String title = "Confirm";
        int reply = JOptionPane.showConfirmDialog(null, message, title, JOptionPane.YES_NO_OPTION);
        if (reply == JOptionPane.YES_OPTION) {
            try {
                String query = "delete from vehicleRepairs";
                stat =  (PreparedStatement) connect.prepareStatement(query);
                stat.executeUpdate();
                JOptionPane.showMessageDialog(null,"Data deleted successfully");
                stat.close();
            } catch (Exception ex) {
                JOptionPane.showMessageDialog(null, ex);
            }
        }
        updateRepair(); //Update the table
        clearRepair(); // Empty the textfields
    }//GEN-LAST:event_delAllButtonActionPerformed

    private void delRepButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_delRepButtonActionPerformed
        String message = " Are you sure want to delete the data?";
        String title = "Confirm";
        int reply = JOptionPane.showConfirmDialog(null, message, title, JOptionPane.YES_NO_OPTION);
        if (reply == JOptionPane.YES_OPTION) {
            try{
                String query = "delete from vehicleRepairs where RepairsID =?";
                stat =  (PreparedStatement) connect.prepareStatement(query);
                stat.setString(1, rIDTextField.getText());
                stat.execute();
                JOptionPane.showMessageDialog(null,"Data deleted successfully");
                stat.close();
            }
            catch(Exception ex){
                JOptionPane.showMessageDialog(null, ex);
            }
            updateRepair(); //Update the table
            clearRepair();  // Empty the textfields
        }
    }//GEN-LAST:event_delRepButtonActionPerformed

    private void updateButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateButtonActionPerformed
        String message = " Are you sure want to update the data?";
        String title = "Update Data";
        int reply = JOptionPane.showConfirmDialog(null, message, title, JOptionPane.YES_NO_OPTION);
        if (reply == JOptionPane.YES_OPTION) {
            try{
                String id = rIDTextField.getText();
                String mec = mecIDTextField.getText();
                String vec = vecTextField.getText();
                String nam = pNamTextField.getText();
                String pID = pIDTextField.getText();
                String iDate = iDateTextField.getText();
                String wDate = wDateTextField.getText();
                String query ="update vehicleRepairs set RepairsID='"+id+"',mechanicID='"+mec+" ', vehicleID='"+vec+"',PartID='"+pID+"',partName='"+nam+"',dateInstalled='"+iDate+"', dateWarranty ='"+wDate+"' where RepairsID='"+id+"' ";
                stat = (PreparedStatement) connect.prepareStatement(query);
                stat.execute();
                JOptionPane.showMessageDialog(null, "Data Updated Successfully");
                stat.close();
            }
            catch(Exception ex){
                JOptionPane.showMessageDialog(null, ex);
            }
            updateRepair();
        }
    }//GEN-LAST:event_updateButtonActionPerformed
    
    //MENU BUTTONS
    private void orderButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_orderButtonActionPerformed
        ordersGui order = new ordersGui();
        order.setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_orderButtonActionPerformed

    private void trackButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_trackButtonActionPerformed
        trackGui track = new trackGui();
        track.setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_trackButtonActionPerformed

    private void repGUIButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_repGUIButtonActionPerformed
        newRepair rep = new newRepair();
        rep.setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_repGUIButtonActionPerformed

    private void listButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_listButtonActionPerformed
        summaryList li = new summaryList();
        li.setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_listButtonActionPerformed

    private void tpsMenuButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tpsMenuButtonActionPerformed
        thirdPartySuppliersGui tps = new thirdPartySuppliersGui();
        tps.setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_tpsMenuButtonActionPerformed

    private void parMenButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_parMenButtonActionPerformed
        partsGui g = new partsGui();
        g.setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_parMenButtonActionPerformed

    private void wDateTextFieldMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_wDateTextFieldMouseClicked
        String iDate = iDateTextField.getText();
        Date date = new Date();
        SimpleDateFormat dateFormat = new SimpleDateFormat("dd/MM/yyyy");
        dateFormat.applyPattern("dd/MM/yyyy");
        try{
            date=dateFormat.parse(iDate);
            Calendar cal = Calendar.getInstance();
            cal.setTime(date);
            cal.add(Calendar.YEAR, 1);
            date = cal.getTime();
            wDateTextField.setText(dateFormat.format(date));
        }
        catch(Exception ex){
            JOptionPane.showMessageDialog(null,"Enter the installed date above");
        }
    }//GEN-LAST:event_wDateTextFieldMouseClicked

    private void pNamTextFieldMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pNamTextFieldMouseClicked
   
     checkStock();
        String partVal = pIDTextField.getText();
        try{
            
            int part_click = Integer.parseInt(partVal);
            String query = "select * from Parts where PartID='"+part_click+"' ";
            try{
                stat = (PreparedStatement) connect.prepareStatement(query);
                res = stat.executeQuery();
                if(res.next())
               {
                    String addPart=res.getString("Partname");
                    pNamTextField.setText(addPart);
                }
                stat.close();
                res.close();
            }
            catch(Exception ex){
                JOptionPane.showMessageDialog(null,ex);
            }
        }
        
        catch(Exception ex){
            JOptionPane.showMessageDialog(null,"Enter Part ID");
        
        }
    
    }//GEN-LAST:event_pNamTextFieldMouseClicked
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
        * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
        */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(newRepair.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(newRepair.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(newRepair.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(newRepair.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new newRepair().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addRepButton;
    private javax.swing.JButton clrButton;
    private javax.swing.JButton delAllButton;
    private javax.swing.JButton delRepButton;
    private javax.swing.JFormattedTextField iDateTextField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton listButton;
    private javax.swing.JTextField mecIDTextField;
    private javax.swing.JPanel menuPanel;
    private javax.swing.JButton orderButton;
    private javax.swing.JTextField pIDTextField;
    private javax.swing.JTextField pNamTextField;
    private javax.swing.JButton parMenButton;
    private javax.swing.JTextField rIDTextField;
    private javax.swing.JButton repGUIButton;
    private javax.swing.JTable repTable;
    private javax.swing.JButton tpsMenuButton;
    private javax.swing.JButton trackButton;
    private javax.swing.JButton updateButton;
    private javax.swing.JTextField vecTextField;
    private javax.swing.JFormattedTextField wDateTextField;
    // End of variables declaration//GEN-END:variables
}
