/*
* To change this license header, choose License Headers in Project Properties.
* To change this template file, choose Tools | Templates
* and open the template in the editor.
*/

package partsproject;

/**
 * @author jpma3
 */

/* import the package from java library*/
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import net.proteanit.sql.DbUtils;

public class ordersGui extends javax.swing.JFrame {
    // initialize variables for database connection
    Connection connect = null;
    ResultSet res = null;
    PreparedStatement stat = null;

    private void updateOrder(){
        String query1 = "select ordersID,thirdPartySuppliersID,PartID,MechanicID,expectedDeliveryDate,partsName,partsDescription,Quantity from Orders";
        try {
            stat =  (PreparedStatement) connect.prepareStatement(query1);
            res = stat.executeQuery();
            orderTable.setModel(DbUtils.resultSetToTableModel(res));
            res.close(); 
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null,ex);
        }
    }
    
    private void clearOrders(){
    /* set null value to clear all textfields */
        oIDLabel.setText(null);
        desTextField.setText(null);
        namTextField.setText(null);
        TPSidTextField.setText(null);
        mecTextField.setText(null);
        dateTextField.setText(null);
        partIDTextField.setText(null);
        qTextField.setText(null);
    }
    /**
     * Creates new form ordersGui
     */
    public ordersGui() {
        connect = dbConnect.databaseconnect(); // connect to the sqllite database
        initComponents();
        updateOrder(); //update the orders table
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        ordersPanel = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        orderTable = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        TPSidTextField = new javax.swing.JTextField();
        mecTextField = new javax.swing.JTextField();
        desTextField = new javax.swing.JTextField();
        namTextField = new javax.swing.JTextField();
        partIDTextField = new javax.swing.JTextField();
        clearButton = new javax.swing.JButton();
        addOrderButton = new javax.swing.JButton();
        upButton = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        oIDLabel = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        qTextField = new javax.swing.JTextField();
        dateTextField = new javax.swing.JFormattedTextField();
        delAllButton = new javax.swing.JButton();
        delOrderButton = new javax.swing.JButton();
        menuPanel = new javax.swing.JPanel();
        orderButton = new javax.swing.JButton();
        trackButton = new javax.swing.JButton();
        repGUIButton = new javax.swing.JButton();
        listButton = new javax.swing.JButton();
        tpsMenuButton = new javax.swing.JButton();
        parMenButton = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        orderTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        orderTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                orderTableMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(orderTable);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Order", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.BELOW_TOP, new java.awt.Font("Lucida Grande", 1, 14))); // NOI18N

        jLabel3.setText("Part ID");

        jLabel2.setText("Part Name");

        jLabel4.setText("Part Description");

        jLabel11.setText("Mechanic ID");

        jLabel5.setText("Third Party Suppliers ID");

        jLabel8.setText("Expected Delivery Date");

        TPSidTextField.setText("\"4\"");

        mecTextField.setText("\"2\"");

        desTextField.setEditable(false);

        namTextField.setEditable(false);

        partIDTextField.setText("\"1\"");
        partIDTextField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                partIDTextFieldKeyReleased(evt);
            }
        });

        clearButton.setText("Clear");
        clearButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearButtonActionPerformed(evt);
            }
        });

        addOrderButton.setText("Order");
        addOrderButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addOrderButtonActionPerformed(evt);
            }
        });

        upButton.setText("Update");
        upButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                upButtonActionPerformed(evt);
            }
        });

        jLabel6.setText("Order ID");

        oIDLabel.setText("ID");

        jLabel1.setText("Quantity");

        qTextField.setText("\"4\"");

        dateTextField.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter(new java.text.SimpleDateFormat("dd/MM/yyyy"))));
        dateTextField.setText("dd/mm/yyyy");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(jLabel11)
                    .addComponent(jLabel2)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6)
                    .addComponent(jLabel8)
                    .addComponent(jLabel1)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(addOrderButton, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(clearButton, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(oIDLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(dateTextField, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 149, Short.MAX_VALUE)
                        .addComponent(qTextField, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(TPSidTextField, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(mecTextField, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(desTextField, javax.swing.GroupLayout.Alignment.LEADING))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(upButton, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(namTextField, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(partIDTextField, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 148, Short.MAX_VALUE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(oIDLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(partIDTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(namTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(desTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(mecTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TPSidTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(qTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(dateTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addOrderButton)
                    .addComponent(clearButton)
                    .addComponent(upButton))
                .addGap(0, 0, Short.MAX_VALUE))
        );

        delAllButton.setText("Delete All");
        delAllButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                delAllButtonActionPerformed(evt);
            }
        });

        delOrderButton.setText("Delete");
        delOrderButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                delOrderButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout ordersPanelLayout = new javax.swing.GroupLayout(ordersPanel);
        ordersPanel.setLayout(ordersPanelLayout);
        ordersPanelLayout.setHorizontalGroup(
            ordersPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ordersPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addGroup(ordersPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ordersPanelLayout.createSequentialGroup()
                        .addComponent(delAllButton)
                        .addGap(30, 30, 30)
                        .addComponent(delOrderButton)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 489, Short.MAX_VALUE))
                .addContainerGap())
        );
        ordersPanelLayout.setVerticalGroup(
            ordersPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ordersPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(ordersPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ordersPanelLayout.createSequentialGroup()
                        .addGroup(ordersPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(delAllButton)
                            .addComponent(delOrderButton))
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                    .addGroup(ordersPanelLayout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );

        menuPanel.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        orderButton.setText("Orders");
        orderButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                orderButtonActionPerformed(evt);
            }
        });

        trackButton.setText("Track");
        trackButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                trackButtonActionPerformed(evt);
            }
        });

        repGUIButton.setText("New Repair");
        repGUIButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                repGUIButtonActionPerformed(evt);
            }
        });

        listButton.setText("Summary List");
        listButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                listButtonActionPerformed(evt);
            }
        });

        tpsMenuButton.setText("Third Party Suppliers");
        tpsMenuButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tpsMenuButtonActionPerformed(evt);
            }
        });

        parMenButton.setText("Parts");
        parMenButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                parMenButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout menuPanelLayout = new javax.swing.GroupLayout(menuPanel);
        menuPanel.setLayout(menuPanelLayout);
        menuPanelLayout.setHorizontalGroup(
            menuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(menuPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(menuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(orderButton, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(trackButton, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(repGUIButton, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(listButton, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(tpsMenuButton, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(parMenButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        menuPanelLayout.setVerticalGroup(
            menuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(menuPanelLayout.createSequentialGroup()
                .addGap(7, 7, 7)
                .addComponent(parMenButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(orderButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(trackButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(repGUIButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(listButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tpsMenuButton)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Orders", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.BELOW_TOP, new java.awt.Font("Lucida Grande", 0, 24))); // NOI18N

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(menuPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(ordersPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ordersPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(51, 51, 51)
                        .addComponent(menuPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // order parts
    private void addOrderButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addOrderButtonActionPerformed
     String message = "Are you sure want to order the data?";
     String title = "New Order";
     int reply = JOptionPane.showConfirmDialog(null, message, title, JOptionPane.YES_NO_OPTION);
     if (reply == JOptionPane.YES_OPTION) {          
        String query2 = "insert into Orders(ordersID,thirdPartySuppliersID,PartID,MechanicID,expectedDeliveryDate,partsName,partsDescription,Quantity) values (?,?,?,?,?,?,?,?) ";
        try{
            stat =  (PreparedStatement) connect.prepareStatement(query2);
            stat.setString(2,TPSidTextField.getText());
            stat.setString(3,partIDTextField.getText());
            stat.setString(4,mecTextField.getText());
            stat.setString(5,dateTextField.getText());
            stat.setString(6,namTextField.getText());
            stat.setString(7,desTextField.getText());
            stat.setString(8,qTextField.getText());
            stat.execute();
            JOptionPane.showMessageDialog(null,"Data Saved Succesfully");
            stat.close();
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null,ex);
        }
        updateOrder();
        clearOrders();
     }
    }//GEN-LAST:event_addOrderButtonActionPerformed

    private void partIDTextFieldKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_partIDTextFieldKeyReleased
        String value = partIDTextField.getText();
        String message = "Are you sure want order this " +value+" Part ID ?";
        String title = "Parts InStock";
        String query3 = "select * from Parts where PartID='"+value+"' ";
        try{
            stat = (PreparedStatement) connect.prepareStatement(query3);
            res = stat.executeQuery();
            if(res.next())
            {
                String addN=res.getString("Partname");
                namTextField.setText(addN);
                String addDn=res.getString("description");
                desTextField.setText(addDn);
                String nam = res.getString("partsRemaining");
                if (!nam.equalsIgnoreCase("0"))
                {
                    int response = JOptionPane.showConfirmDialog(null, message, title, JOptionPane.YES_NO_OPTION);
                    if (response == JOptionPane.NO_OPTION) {
                        partIDTextField.setText(null);
                        desTextField.setText(null);
                        namTextField.setText(null);
                        JOptionPane.showMessageDialog(null,"Enter PartID to order"); 
                    }
                } 
            }
            stat.close();
            res.close();  
        }
        catch(Exception ex){
            JOptionPane.showMessageDialog(null, ex);
        } 
    }//GEN-LAST:event_partIDTextFieldKeyReleased

    private void orderTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_orderTableMouseClicked
        
        try{
            
            int row = orderTable.getSelectedRow();
            String orderTable_click = (orderTable.getModel().getValueAt(row, 0).toString());
            String query = "select * from Orders where ordersID ='"+orderTable_click+" ' ";
            stat =  (PreparedStatement) connect.prepareStatement(query);
            
            res = stat.executeQuery();
            
            if (res.next())
            {
                
                String orderID=res.getString("ordersID");
                oIDLabel.setText(orderID);
                String addTPS=res.getString("thirdPartySuppliersID");
                TPSidTextField.setText(addTPS);
                String addMec=res.getString("MechanicID");
                mecTextField.setText(addMec);
                String addID=res.getString("PartID");
                partIDTextField.setText(addID);
                String addDate=res.getString("expectedDeliveryDate");
                dateTextField.setText(addDate);
                String addDes=res.getString("partsName");
                desTextField.setText(addDes);
                String addNam=res.getString("partsDescription");
                namTextField.setText(addNam);
                String addQ=res.getString("Quantity");
                qTextField.setText(addQ);
                
            }
            stat.close();
        }
        
        
        catch(Exception ex){
            JOptionPane.showMessageDialog(null, ex);
        }
    }//GEN-LAST:event_orderTableMouseClicked

    //to clear textfields
    private void clearButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearButtonActionPerformed
      String message = " Are you sure want to clear the data?";
        String title = "Clear Orders";
        int reply = JOptionPane.showConfirmDialog(null, message, title, JOptionPane.YES_NO_OPTION);
        if (reply == JOptionPane.YES_OPTION) {  
        clearOrders();
        }
    }//GEN-LAST:event_clearButtonActionPerformed

    //method to update records
    private void upButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_upButtonActionPerformed
     String message = "Are you sure want to update the data?";
     String title = "Update Orders changes";
     int reply = JOptionPane.showConfirmDialog(null, message, title, JOptionPane.YES_NO_OPTION);
     if (reply == JOptionPane.YES_OPTION) {           
        try{
            String oID = oIDLabel.getText();
            String des = desTextField.getText();
            String nam = namTextField.getText();
            String tpsid = TPSidTextField.getText();
            String mec = mecTextField.getText();
            String date = dateTextField.getText();
            String partid = partIDTextField.getText();
            String q = qTextField.getText();
            String query ="update Orders set ordersID='"+oID+"', PartID='"+partid+"',thirdPartySuppliersID='"+tpsid+"',MechanicID='"+mec+"',partsName='"+nam+" ',partsDescription='"+des+"',expectedDeliveryDate='"+date+"',Quantity='"+q+"' where ordersID='"+oID+"' ";
            
            stat = (PreparedStatement) connect.prepareStatement(query);
            
            stat.execute();
            
            JOptionPane.showMessageDialog(null, "Data Updated");
            
            stat.close();
            
        }
        catch(Exception ex){
            JOptionPane.showMessageDialog(null, ex);
        }
        updateOrder();
     }
    }//GEN-LAST:event_upButtonActionPerformed

    //method to delete all records
    private void delAllButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_delAllButtonActionPerformed
        String message = " Are you sure want to delete all data?";
        String title = "Confirm";
        int reply = JOptionPane.showConfirmDialog(null, message, title, JOptionPane.YES_NO_OPTION);
        if (reply == JOptionPane.YES_OPTION) {
            try {
                
                String query = "delete from Orders";
                
                stat =  (PreparedStatement) connect.prepareStatement(query);
                
                stat.executeUpdate();
                JOptionPane.showMessageDialog(null,"Data deleted successfully");
                
                stat.close();
                
            } catch (Exception ex) {
                JOptionPane.showMessageDialog(null,ex);
            }
            updateOrder();
        clearOrders();
        }
       
    }//GEN-LAST:event_delAllButtonActionPerformed

    //Method to delete orders
    private void delOrderButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_delOrderButtonActionPerformed

        String message = " Are you sure want to delete the data?";
        String title = "Confirm";
        int reply = JOptionPane.showConfirmDialog(null, message, title, JOptionPane.YES_NO_OPTION);
        if (reply == JOptionPane.YES_OPTION) {
            try{
                
                String query = "delete from Orders where ordersID =?";
                stat =  (PreparedStatement) connect.prepareStatement(query);
                stat.setString(1, oIDLabel.getText());
                stat.executeUpdate();
                JOptionPane.showMessageDialog(null,"Data deleted successfully");
                stat.close(); 
            }
            catch(Exception ex){
                JOptionPane.showMessageDialog(null, ex);
            }
        }
          updateOrder();
          clearOrders();
    }//GEN-LAST:event_delOrderButtonActionPerformed

    //Menu buttons
    private void orderButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_orderButtonActionPerformed
        ordersGui order = new ordersGui();       
        order.setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_orderButtonActionPerformed

    private void trackButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_trackButtonActionPerformed
        trackGui track = new trackGui();
        track.setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_trackButtonActionPerformed

    private void repGUIButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_repGUIButtonActionPerformed
        newRepair rep = new newRepair();
        rep.setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_repGUIButtonActionPerformed

    private void listButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_listButtonActionPerformed
        summaryList li = new summaryList();
        li.setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_listButtonActionPerformed

    private void tpsMenuButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tpsMenuButtonActionPerformed
        thirdPartySuppliersGui tps = new thirdPartySuppliersGui();
        tps.setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_tpsMenuButtonActionPerformed

    private void parMenButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_parMenButtonActionPerformed
        partsGui g = new partsGui();
        g.setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_parMenButtonActionPerformed
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
        * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
        */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ordersGui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ordersGui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ordersGui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ordersGui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ordersGui().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField TPSidTextField;
    private javax.swing.JButton addOrderButton;
    private javax.swing.JButton clearButton;
    private javax.swing.JFormattedTextField dateTextField;
    private javax.swing.JButton delAllButton;
    private javax.swing.JButton delOrderButton;
    private javax.swing.JTextField desTextField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JButton listButton;
    private javax.swing.JTextField mecTextField;
    private javax.swing.JPanel menuPanel;
    private javax.swing.JTextField namTextField;
    private javax.swing.JLabel oIDLabel;
    private javax.swing.JButton orderButton;
    private javax.swing.JTable orderTable;
    private javax.swing.JPanel ordersPanel;
    private javax.swing.JButton parMenButton;
    private javax.swing.JTextField partIDTextField;
    private javax.swing.JTextField qTextField;
    private javax.swing.JButton repGUIButton;
    private javax.swing.JButton tpsMenuButton;
    private javax.swing.JButton trackButton;
    private javax.swing.JButton upButton;
    // End of variables declaration//GEN-END:variables
}
