/*
* To change this license header, choose License Headers in Project Properties.
* To change this template file, choose Tools | Templates
* and open the template in the editor.
*/
package partsproject;

/**
 * @author jpma3
 */

/* import the package from java library*/
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;

import net.proteanit.sql.DbUtils;
public class partsGui extends javax.swing.JFrame {
   // initialize variables for database connection
    Connection connect = null;
    ResultSet res = null;
    PreparedStatement stat = null;
    
     /* this method used to clear the text*/
    private void clearTable(){
        idLabel.setText(null);
        desJTextField.setText(null);
        costJTextField.setText(null);
        nameJTextField.setText(null);
        remainJTextField.setText(null);
    }
    
    private void updatePartTable()
    {
        try {
            String query = "select PartID,description,cost,Partname,partsRemaining from Parts";
            stat =  (PreparedStatement) connect.prepareStatement(query);
            res = stat.executeQuery();
            partsJTable.setModel(DbUtils.resultSetToTableModel(res));
            res.close();
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null,ex);
        }
    }
    
    /**
     * Creates new form partsGui
     */
    public partsGui() {
        connect = dbConnect.databaseconnect(); // connect to the sqllite database
        initComponents();
        updatePartTable(); //update the parts table
    }
    
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        partsPanel = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        partDesJLabel = new javax.swing.JLabel();
        partCostJLabel = new javax.swing.JLabel();
        partNameJLabel = new javax.swing.JLabel();
        partRemainJLabel = new javax.swing.JLabel();
        addNewPartJButton = new javax.swing.JButton();
        clearJButton = new javax.swing.JButton();
        tabUpdateButton = new javax.swing.JButton();
        remainJTextField = new javax.swing.JTextField();
        nameJTextField = new javax.swing.JTextField();
        desJTextField = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        idLabel = new javax.swing.JLabel();
        costJTextField = new javax.swing.JFormattedTextField();
        menuPanel = new javax.swing.JPanel();
        orderButton = new javax.swing.JButton();
        trackButton = new javax.swing.JButton();
        repGUIButton = new javax.swing.JButton();
        listButton = new javax.swing.JButton();
        tpsMenuButton = new javax.swing.JButton();
        parMenButton = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        partsJTable = new javax.swing.JTable();
        delAllButton = new javax.swing.JButton();
        deleteButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "New Part", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.BELOW_TOP, new java.awt.Font("Lucida Grande", 1, 18))); // NOI18N

        partDesJLabel.setText("Part Description");

        partCostJLabel.setText("Part Cost");

        partNameJLabel.setText("Part Name");

        partRemainJLabel.setText("Parts Remaining ");

        addNewPartJButton.setText("Add Part");
        addNewPartJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addNewPartJButtonActionPerformed(evt);
            }
        });

        clearJButton.setText("Clear");
        clearJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearJButtonActionPerformed(evt);
            }
        });

        tabUpdateButton.setText("Update");
        tabUpdateButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tabUpdateButtonActionPerformed(evt);
            }
        });

        remainJTextField.setText("\"2\"");

        nameJTextField.setText("\"Glass\"");

        desJTextField.setText("\"Window\"");

        jLabel1.setText("Part ID");

        idLabel.setText("ID");

        costJTextField.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("£#,##0.00;(£#,##0.00)"))));
        costJTextField.setText("\"£0.00\"");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(24, Short.MAX_VALUE)
                .addComponent(addNewPartJButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(clearJButton, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tabUpdateButton)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(partRemainJLabel)
                    .addComponent(partCostJLabel)
                    .addComponent(partNameJLabel)
                    .addComponent(partDesJLabel)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(remainJTextField, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(costJTextField, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 173, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(nameJTextField, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(idLabel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(desJTextField, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 173, Short.MAX_VALUE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(idLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(partNameJLabel)
                    .addComponent(nameJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(partDesJLabel)
                    .addComponent(desJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(partCostJLabel)
                    .addComponent(costJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(partRemainJLabel)
                    .addComponent(remainJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addNewPartJButton)
                    .addComponent(clearJButton)
                    .addComponent(tabUpdateButton))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout partsPanelLayout = new javax.swing.GroupLayout(partsPanel);
        partsPanel.setLayout(partsPanelLayout);
        partsPanelLayout.setHorizontalGroup(
            partsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(partsPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        partsPanelLayout.setVerticalGroup(
            partsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(partsPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        menuPanel.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        orderButton.setText("Orders");
        orderButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                orderButtonActionPerformed(evt);
            }
        });

        trackButton.setText("Track");
        trackButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                trackButtonActionPerformed(evt);
            }
        });

        repGUIButton.setText("New Repair");
        repGUIButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                repGUIButtonActionPerformed(evt);
            }
        });

        listButton.setText("Summary List");
        listButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                listButtonActionPerformed(evt);
            }
        });

        tpsMenuButton.setText("Third Party Suppliers");
        tpsMenuButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tpsMenuButtonActionPerformed(evt);
            }
        });

        parMenButton.setText("Parts");
        parMenButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                parMenButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout menuPanelLayout = new javax.swing.GroupLayout(menuPanel);
        menuPanel.setLayout(menuPanelLayout);
        menuPanelLayout.setHorizontalGroup(
            menuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(menuPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(menuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(orderButton, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(trackButton, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(repGUIButton, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(listButton, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(tpsMenuButton, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(parMenButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        menuPanelLayout.setVerticalGroup(
            menuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(menuPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(parMenButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(orderButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(trackButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(repGUIButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(listButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tpsMenuButton)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Parts", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.BELOW_TOP, new java.awt.Font("Lucida Grande", 0, 24))); // NOI18N

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        partsJTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Part ID", "Part Name", "Part Description", "Part Cost", "Parts Remaining"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.Integer.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        partsJTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                partsJTableMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(partsJTable);

        delAllButton.setText("Delete All");
        delAllButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                delAllButtonActionPerformed(evt);
            }
        });

        deleteButton.setText("Delete");
        deleteButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(menuPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(partsPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(deleteButton, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(delAllButton, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 514, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 9, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 12, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(menuPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(deleteButton)
                                .addComponent(delAllButton))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(partsPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void delAllButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_delAllButtonActionPerformed
        String message = " Are you sure want to delete all data?";
        String title = "Confirm";
        int reply = JOptionPane.showConfirmDialog(null, message, title, JOptionPane.YES_NO_OPTION);
        if (reply == JOptionPane.YES_OPTION) {
            try {
                
                String query = "delete from Parts";
                
                stat =  (PreparedStatement) connect.prepareStatement(query);
                
                stat.executeUpdate();
                JOptionPane.showMessageDialog(null,"Part deleted successfully");
                
                stat.close();
                
            } catch (Exception ex) {
               JOptionPane.showMessageDialog(null,ex);
            }
             updatePartTable();
        }
   
    }//GEN-LAST:event_delAllButtonActionPerformed

    private void addNewPartJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addNewPartJButtonActionPerformed
        String message = "Are you sure want to add the data?";
        String title = "Add new part";
        int reply = JOptionPane.showConfirmDialog(null, message, title, JOptionPane.YES_NO_OPTION);
        if (reply == JOptionPane.YES_OPTION) {
        try {
            String query = "insert into Parts (PartID,description,cost,Partname,partsRemaining) values (?,?,?,?,?) ";
            stat =  (PreparedStatement) connect.prepareStatement(query);
            stat.setString(2,desJTextField.getText());
            stat.setString(3,costJTextField.getText());
            stat.setString(4,nameJTextField.getText());
            stat.setString(5,remainJTextField.getText());
            stat.execute();
            JOptionPane.showMessageDialog(null,"Part added succesfully");
            stat.close();
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null,ex);
        }
        updatePartTable(); //update part table
        clearTable(); //clear the textfields
        }
    }//GEN-LAST:event_addNewPartJButtonActionPerformed

    private void clearJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearJButtonActionPerformed
        String message = "Are you sure want to clear the data?";
        String title = "Clear data";
        int reply = JOptionPane.showConfirmDialog(null, message, title, JOptionPane.YES_NO_OPTION);
        if (reply == JOptionPane.YES_OPTION) {      
        clearTable();
        }
    }//GEN-LAST:event_clearJButtonActionPerformed

    private void partsJTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_partsJTableMouseClicked
        try{
            
            int row = partsJTable.getSelectedRow();
            String partsTable_click = (partsJTable.getModel().getValueAt(row, 0).toString());
            String query = "select * from Parts where PartID='"+partsTable_click+" ' ";
            stat =  (PreparedStatement) connect.prepareStatement(query);
            res = stat.executeQuery();
            
            if (res.next())
            {
                
                String partID=res.getString("PartID");
                idLabel.setText(partID);
                String addDes=res.getString("description");
                desJTextField.setText(addDes);
                String addCost=res.getString("cost");
                costJTextField.setText(addCost);
                String addNam=res.getString("partname");
                nameJTextField.setText(addNam);
                String addRem=res.getString("partsRemaining");
                remainJTextField.setText(addRem);
                
            }
            stat.close();
        }
        
        
        catch(Exception ex){
            
            JOptionPane.showMessageDialog(null, ex);
        }
        
    }//GEN-LAST:event_partsJTableMouseClicked

    private void tabUpdateButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tabUpdateButtonActionPerformed
          String message = "Are you sure want to update the data?";
          String title = "Update part changes";
          int reply = JOptionPane.showConfirmDialog(null, message, title, JOptionPane.YES_NO_OPTION);
          if (reply == JOptionPane.YES_OPTION) {        
          try{
            String pID = idLabel.getText();
            String des = desJTextField.getText();
            String cost = costJTextField.getText();
            String name = nameJTextField.getText();
            String rem = remainJTextField.getText();
            String query ="update Parts set PartID='"+pID+"',description='"+des+"',cost='"+cost+" ', partname='"+name+"',partsRemaining='"+rem+"' where  PartID='"+pID+"'";
            stat = (PreparedStatement) connect.prepareStatement(query);
            stat.execute();
            JOptionPane.showMessageDialog(null, "Part updated");
            stat.close();
        }
        catch(Exception ex){
            JOptionPane.showMessageDialog(null, ex);
        }
        updatePartTable(); //update part table
        clearTable(); //clear the textfields
        }
    }//GEN-LAST:event_tabUpdateButtonActionPerformed

    private void deleteButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteButtonActionPerformed
        
        
        String message = " Are you sure want to delete the data?";
        String title = "Confirm";
        int reply = JOptionPane.showConfirmDialog(null, message, title, JOptionPane.YES_NO_OPTION);
        if (reply == JOptionPane.YES_OPTION) {
            
            
            try{
                
                String query = "delete from Parts where PartID =?";
                
                stat =  (PreparedStatement) connect.prepareStatement(query);
                stat.setString(1, idLabel.getText());
                
                stat.execute();
                JOptionPane.showMessageDialog(null,"Part deleted successfully");
                
                stat.close();
                
            }
            
            
            catch(Exception ex){
                JOptionPane.showMessageDialog(null, ex);
            }
            
            updatePartTable();
            clearTable();
        }
    }//GEN-LAST:event_deleteButtonActionPerformed

    private void trackButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_trackButtonActionPerformed
/* To open the trackGui form */        
        trackGui track = new trackGui();
        track.setVisible(true); //Show only the trackGui
        setVisible(false); //Close other Gui
    }//GEN-LAST:event_trackButtonActionPerformed

    private void repGUIButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_repGUIButtonActionPerformed
/* To open the newRepairs GUI form */        
        newRepair rep = new newRepair();
        rep.setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_repGUIButtonActionPerformed

    private void orderButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_orderButtonActionPerformed
/* To open the ordersGui form */
        ordersGui order = new ordersGui();
        order.setVisible(true);
        setVisible(false);  
    }//GEN-LAST:event_orderButtonActionPerformed

    private void listButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_listButtonActionPerformed
 /* To open the summaryList form */       
        summaryList li = new summaryList();
        li.setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_listButtonActionPerformed

    private void parMenButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_parMenButtonActionPerformed
/* To open the partsGui form */       
        partsGui g = new partsGui();
        g.setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_parMenButtonActionPerformed

    private void tpsMenuButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tpsMenuButtonActionPerformed
/* To open the thirdPartySuppliersGui form */
        thirdPartySuppliersGui tps = new thirdPartySuppliersGui();
        tps.setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_tpsMenuButtonActionPerformed
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
        * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
        */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(partsGui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(partsGui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(partsGui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(partsGui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new partsGui().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addNewPartJButton;
    private javax.swing.JButton clearJButton;
    private javax.swing.JFormattedTextField costJTextField;
    private javax.swing.JButton delAllButton;
    private javax.swing.JButton deleteButton;
    private javax.swing.JTextField desJTextField;
    private javax.swing.JLabel idLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JButton listButton;
    private javax.swing.JPanel menuPanel;
    private javax.swing.JTextField nameJTextField;
    private javax.swing.JButton orderButton;
    private javax.swing.JButton parMenButton;
    private javax.swing.JLabel partCostJLabel;
    private javax.swing.JLabel partDesJLabel;
    private javax.swing.JLabel partNameJLabel;
    private javax.swing.JLabel partRemainJLabel;
    private javax.swing.JTable partsJTable;
    private javax.swing.JPanel partsPanel;
    private javax.swing.JTextField remainJTextField;
    private javax.swing.JButton repGUIButton;
    private javax.swing.JButton tabUpdateButton;
    private javax.swing.JButton tpsMenuButton;
    private javax.swing.JButton trackButton;
    // End of variables declaration//GEN-END:variables
}
