/*
* To change this license header, choose License Headers in Project Properties.
* To change this template file, choose Tools | Templates
* and open the template in the editor.
*/
package partsproject;

/**
 * @author jpma3
 */

/* import the package from java library*/
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import net.proteanit.sql.DbUtils;


public class thirdPartySuppliersGui extends javax.swing.JFrame {
 // initialize variables for database connection
    Connection connect = null;
    ResultSet res = null;
    PreparedStatement stat = null;
    
    /**
     * Creates new form thirdPartySuppliersGui
     */
    public thirdPartySuppliersGui() {
        connect = dbConnect.databaseconnect(); //connect to the sqllite database
        initComponents();
        updateTPS(); //upadate thirdpartysuppliers table
        updateAddressTable(); //upadate address table
        updateTPart(); //upadate thirdpartysuppliersparts table
    }
    
    /* this method used to clear the text*/
    private void clearTps(){
        tpsLabel.setText(null);
        firstNameTextField.setText(null);
        lastNameTextField.setText(null);
        phoneTextField.setText(null);
        addIDTextField.setText(null);
    }
    
    /* this method used to clear the text*/
    private void clearAddress(){
        addIDLabel.setText(null);
        firstLineTextField.setText(null);
        countyTextField.setText(null);
        postcodeTextField.setText(null);
    }
    
    private void updateTPart(){
        String query = "select TrackID,thirdPartySuppliersID from Track";
        try {
            stat = (PreparedStatement) connect.prepareStatement(query);
            res = stat.executeQuery();
            tPartTable.setModel(DbUtils.resultSetToTableModel(res));
            stat.close();
        } catch (Exception ex) {
             JOptionPane.showMessageDialog(null,ex);
        }
    }
    
    private void updateTPS() {
        String query = "select thirdPartyID,Firstname,Lastname,Phonenumber,addressID from ThirdPartySuppliers";
        try {
            stat = (PreparedStatement) connect.prepareStatement(query);
            res = stat.executeQuery();
            tpsTable.setModel(DbUtils.resultSetToTableModel(res));
            stat.close();
        } catch (Exception ex) {
             JOptionPane.showMessageDialog(null,ex);
        }
    }
    
    private void updateAddressTable() {
        String query = "select ThirdPartyAddressID,FirstLineAddress,County,Postcode from Address";
        try {
            stat = (PreparedStatement) connect.prepareStatement(query);
            res = stat.executeQuery();
            addTable.setModel(DbUtils.resultSetToTableModel(res));
            stat.close();
            res.close();
        } catch (Exception ex) {
             JOptionPane.showMessageDialog(null,ex);
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        supPanel = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tpsTable = new javax.swing.JTable();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jScrollPane1 = new javax.swing.JScrollPane();
        addTable = new javax.swing.JTable();
        delAllButton = new javax.swing.JButton();
        deleteButton = new javax.swing.JButton();
        delAllAddButton = new javax.swing.JButton();
        delAddButton = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        addTPSButton = new javax.swing.JButton();
        clearTPSButton = new javax.swing.JButton();
        editButton = new javax.swing.JButton();
        addIDTextField = new javax.swing.JTextField();
        phoneTextField = new javax.swing.JTextField();
        lastNameTextField = new javax.swing.JTextField();
        firstNameTextField = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        firstLineTextField = new javax.swing.JTextField();
        countyTextField = new javax.swing.JTextField();
        addAddressButton = new javax.swing.JButton();
        clearAddressButton = new javax.swing.JButton();
        updateButton = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        tpsLabel = new javax.swing.JLabel();
        addIDLabel = new javax.swing.JLabel();
        postcodeTextField = new javax.swing.JFormattedTextField();
        menuPanel = new javax.swing.JPanel();
        orderButton = new javax.swing.JButton();
        trackButton = new javax.swing.JButton();
        repGUIButton = new javax.swing.JButton();
        listButton = new javax.swing.JButton();
        tpsMenuButton = new javax.swing.JButton();
        parMenButton = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        tPartTable = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tpsTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "ThirdPartySuppliers ID", "First Name", "Last Name", "AddressID", "Contact Number"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.Integer.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        tpsTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tpsTableMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(tpsTable);

        addTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "AddressID", "AddressLine1", "County", "PostCode"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        addTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                addTableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(addTable);

        delAllButton.setText("Delete All");
        delAllButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                delAllButtonActionPerformed(evt);
            }
        });

        deleteButton.setText("Delete");
        deleteButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteButtonActionPerformed(evt);
            }
        });

        delAllAddButton.setText("Delete All");
        delAllAddButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                delAllAddButtonActionPerformed(evt);
            }
        });

        delAddButton.setText("Delete");
        delAddButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                delAddButtonActionPerformed(evt);
            }
        });

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Third Party Suppliers", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.BELOW_TOP, new java.awt.Font("Lucida Grande", 1, 18))); // NOI18N

        jLabel17.setText("First Name");

        jLabel18.setText("Last Name");

        jLabel19.setText("Phone Number");

        jLabel20.setText("Address ID");

        addTPSButton.setText("Add");
        addTPSButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addTPSButtonActionPerformed(evt);
            }
        });

        clearTPSButton.setText("Clear");
        clearTPSButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearTPSButtonActionPerformed(evt);
            }
        });

        editButton.setText("Update");
        editButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editButtonActionPerformed(evt);
            }
        });

        addIDTextField.setText("\"2\"");
        addIDTextField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                addIDTextFieldKeyReleased(evt);
            }
        });

        phoneTextField.setText("\"0208 546 7890\"");

        lastNameTextField.setText("\"May\"");

        firstNameTextField.setText("\"James\"");

        jLabel4.setText("County");

        jLabel5.setText("Postcode");

        jLabel3.setText("First Line Address Line ");

        firstLineTextField.setText("\"44 Brook Road\"");

        countyTextField.setText("\"Essex\"");

        addAddressButton.setText("Add");
        addAddressButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addAddressButtonActionPerformed(evt);
            }
        });

        clearAddressButton.setText("Clear");
        clearAddressButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearAddressButtonActionPerformed(evt);
            }
        });

        updateButton.setText("Update");
        updateButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateButtonActionPerformed(evt);
            }
        });

        jLabel2.setText("Third Party Suppliers ID");

        jLabel6.setText("Address ID");

        tpsLabel.setText("tpsID");

        addIDLabel.setText("ID");

        try {
            postcodeTextField.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("UU## #UU")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        postcodeTextField.setText("RM11 7DF");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel20)
                                    .addComponent(jLabel18))
                                .addGap(103, 103, 103)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(phoneTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lastNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(addIDTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(firstNameTextField)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel17)
                                    .addComponent(jLabel19))
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(tpsLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(35, 35, 35))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(addTPSButton)
                        .addGap(34, 34, 34)
                        .addComponent(clearTPSButton)
                        .addGap(34, 34, 34)
                        .addComponent(editButton)))
                .addGap(27, 27, 27)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(addAddressButton)
                        .addGap(29, 29, 29)
                        .addComponent(clearAddressButton)
                        .addGap(27, 27, 27)
                        .addComponent(updateButton))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(27, 27, 27)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(firstLineTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(8, 8, 8)
                                        .addComponent(addIDLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(countyTextField, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(postcodeTextField, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tpsLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel17)
                            .addComponent(firstNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel18)
                            .addComponent(lastNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel19)
                            .addComponent(phoneTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel20)
                            .addComponent(addIDTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(clearTPSButton)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(addTPSButton)
                                .addComponent(editButton)
                                .addComponent(addAddressButton)
                                .addComponent(clearAddressButton)
                                .addComponent(updateButton))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(addIDLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(firstLineTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(countyTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(postcodeTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(0, 2, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout supPanelLayout = new javax.swing.GroupLayout(supPanel);
        supPanel.setLayout(supPanelLayout);
        supPanelLayout.setHorizontalGroup(
            supPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(supPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(supPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(deleteButton, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(delAllButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 352, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(supPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(supPanelLayout.createSequentialGroup()
                        .addGap(369, 369, 369)
                        .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(supPanelLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(supPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(delAddButton, javax.swing.GroupLayout.DEFAULT_SIZE, 97, Short.MAX_VALUE)
                            .addComponent(delAllAddButton, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, supPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(59, 59, 59))
        );
        supPanelLayout.setVerticalGroup(
            supPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(supPanelLayout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(supPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(supPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(supPanelLayout.createSequentialGroup()
                            .addGap(31, 31, 31)
                            .addComponent(deleteButton)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(delAllButton))
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 133, Short.MAX_VALUE)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                    .addGroup(supPanelLayout.createSequentialGroup()
                        .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(24, 24, 24)
                        .addComponent(delAddButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(delAllAddButton)))
                .addGap(0, 0, Short.MAX_VALUE))
        );

        menuPanel.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        orderButton.setText("Orders");
        orderButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                orderButtonActionPerformed(evt);
            }
        });

        trackButton.setText("Track");
        trackButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                trackButtonActionPerformed(evt);
            }
        });

        repGUIButton.setText("New Repair");
        repGUIButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                repGUIButtonActionPerformed(evt);
            }
        });

        listButton.setText("Summary List");
        listButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                listButtonActionPerformed(evt);
            }
        });

        tpsMenuButton.setText("Third Party Suppliers");
        tpsMenuButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tpsMenuButtonActionPerformed(evt);
            }
        });

        parMenButton.setText("Parts");
        parMenButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                parMenButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout menuPanelLayout = new javax.swing.GroupLayout(menuPanel);
        menuPanel.setLayout(menuPanelLayout);
        menuPanelLayout.setHorizontalGroup(
            menuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(menuPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(menuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(orderButton, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(repGUIButton, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(listButton, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(tpsMenuButton, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(trackButton, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(parMenButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        menuPanelLayout.setVerticalGroup(
            menuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(menuPanelLayout.createSequentialGroup()
                .addComponent(parMenButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(orderButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(trackButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(repGUIButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(listButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tpsMenuButton)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        tPartTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "ThirdPartySuppliersID", "PartID"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.Integer.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane4.setViewportView(tPartTable);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(menuPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(supPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(menuPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(supPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void addTPSButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addTPSButtonActionPerformed
        String message = "Are you sure want to add the data?";
        String title = "Add new suppliers";
        int reply = JOptionPane.showConfirmDialog(null, message, title, JOptionPane.YES_NO_OPTION);
        if (reply == JOptionPane.YES_OPTION) {     
        String query = "insert into ThirdPartySuppliers(thirdPartyID,Firstname,Lastname,Phonenumber,addressID) values(?,?,?,?,?) ";
        try {
            stat = (PreparedStatement) connect.prepareStatement(query);
            stat.setString(2, firstNameTextField.getText());
            stat.setString(3, lastNameTextField.getText());
            stat.setString(4, phoneTextField.getText());
            stat.setString(5, addIDTextField.getText());
            stat.execute();            
            JOptionPane.showMessageDialog(null, "Data Saved Succesfully");            
            stat.close();           
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null,ex);
        }        
        updateTPS();
        clearTps();
        }
    }//GEN-LAST:event_addTPSButtonActionPerformed

    private void clearTPSButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearTPSButtonActionPerformed
        String message = "Are you sure want to clear the data?";
        String title = "Clear data";
        int reply = JOptionPane.showConfirmDialog(null, message, title, JOptionPane.YES_NO_OPTION);
        if (reply == JOptionPane.YES_OPTION) {     
        clearTps();
        }
    }//GEN-LAST:event_clearTPSButtonActionPerformed

    private void addAddressButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addAddressButtonActionPerformed
        String message = "Are you sure want to add the data?";
        String title = "Add new address";
        int reply = JOptionPane.showConfirmDialog(null, message, title, JOptionPane.YES_NO_OPTION);
        if (reply == JOptionPane.YES_OPTION) {     
        String query = "insert into Address(ThirdPartyAddressID,FirstLineAddress,County,Postcode) values(?,?,?,?) ";
        try {
            stat = (PreparedStatement) connect.prepareStatement(query);
            stat.setString(2, firstLineTextField.getText());
            stat.setString(3, countyTextField.getText());
            stat.setString(4, postcodeTextField.getText());         
            stat.execute();     
            JOptionPane.showMessageDialog(null, "Data Saved Succesfully");    
            stat.close();
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null,ex);
        }
        updateAddressTable();
        clearAddress();
        }
    }//GEN-LAST:event_addAddressButtonActionPerformed

    private void clearAddressButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearAddressButtonActionPerformed
       String message = "Are you sure want to clear the data?";
        String title = "Clear data";
        int reply = JOptionPane.showConfirmDialog(null, message, title, JOptionPane.YES_NO_OPTION);
        if (reply == JOptionPane.YES_OPTION) {     
        clearAddress();
        }
    }//GEN-LAST:event_clearAddressButtonActionPerformed

    private void delAllButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_delAllButtonActionPerformed
        String message = " Are you sure?";
        String title = "confirm";
        int reply = JOptionPane.showConfirmDialog(null, message, title, JOptionPane.YES_NO_OPTION);
        if (reply == JOptionPane.YES_OPTION) {
            String query = "delete from ThirdPartySuppliers";
            
            try {
                
                stat = (PreparedStatement) connect.prepareStatement(query);
                
                stat.executeUpdate();
                JOptionPane.showMessageDialog(null, "Data deleted successfully");
                stat.close();
            } catch (Exception ex) {
                 JOptionPane.showMessageDialog(null,ex);
            }
            
            updateTPS();
            
        }
        

    }//GEN-LAST:event_delAllButtonActionPerformed

    private void tpsTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tpsTableMouseClicked
        
        try {
            
            int rows = tpsTable.getSelectedRow();
            String table_click = (tpsTable.getModel().getValueAt(rows, 0).toString());
            
            String query = "select * from ThirdPartySuppliers where thirdPartyID='" + table_click + " ' ";
            
            stat = (PreparedStatement) connect.prepareStatement(query);
            
            res = stat.executeQuery();
            
            if (res.next()) {
                
                String addID = res.getString("thirdPartyID");
                tpsLabel.setText(addID);
                String addFn = res.getString("Firstname");
                firstNameTextField.setText(addFn);
                String addLn = res.getString("Lastname");
                lastNameTextField.setText(addLn);
                String addPn = res.getString("Phonenumber");
                phoneTextField.setText(addPn);
                String addAddressID = res.getString("addressID");
                addIDTextField.setText(addAddressID);
            }
            stat.close();
        } catch (Exception ex) {
            
            JOptionPane.showMessageDialog(null, ex);
        }
        

    }//GEN-LAST:event_tpsTableMouseClicked

    private void addTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addTableMouseClicked
        
        try {
            
            int rows = addTable.getSelectedRow();
            String addTable_click = (addTable.getModel().getValueAt(rows, 0).toString());
            
            String query = "select * from Address where ThirdPartyAddressID='" + addTable_click + " ' ";
            
            stat = (PreparedStatement) connect.prepareStatement(query);
            
            res = stat.executeQuery();
            
            if (res.next()) {
                
                String addAddressID = res.getString("ThirdPartyAddressID");
                addIDLabel.setText(addAddressID);
                String addAL1 = res.getString("FirstLineAddress");
                firstLineTextField.setText(addAL1);
                String addCounty = res.getString("County");
                countyTextField.setText(addCounty);
                String addPc = res.getString("Postcode");
                postcodeTextField.setText(addPc);
                
                
                
                
            }
            stat.close();
        } catch (Exception ex) {
            
            JOptionPane.showMessageDialog(null, ex);
        }
        
        
        
        
    }//GEN-LAST:event_addTableMouseClicked

    private void editButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editButtonActionPerformed
        String message = "Are you sure want to update the data?";
        String title = "Update suppliers";
        int reply = JOptionPane.showConfirmDialog(null, message, title, JOptionPane.YES_NO_OPTION);
        if (reply == JOptionPane.YES_OPTION) {     
        try {
            
            String tps = tpsLabel.getText();
            String fName = firstNameTextField.getText();
            String lName = lastNameTextField.getText();
            String pNumber = phoneTextField.getText();
            String addID = addIDTextField.getText();
            
            String q = "update ThirdPartySuppliers set thirdPartyID='"+tps+"', Firstname='" + fName + "',Lastname='" + lName + " ', phoneNumber='" + pNumber + "',addressID='" + addID + "' where thirdPartyID='"+tps+"' ";
            
            stat = (PreparedStatement) connect.prepareStatement(q);
            
            stat.execute();
            
            JOptionPane.showMessageDialog(null, "Data updated");
            
            stat.close();
            
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, ex);
        }
        
        updateTPS();
        clearTps();
        }
    }//GEN-LAST:event_editButtonActionPerformed

    private void updateButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateButtonActionPerformed
        String message = "Are you sure want to update the data?";
        String title = "Update Address";
        int reply = JOptionPane.showConfirmDialog(null, message, title, JOptionPane.YES_NO_OPTION);
        if (reply == JOptionPane.YES_OPTION) {              
        try {
            
            String addID = addIDLabel.getText();
            String fAdd = firstLineTextField.getText();
            String county = countyTextField.getText();
            String post = postcodeTextField.getText();
            
            String q = "update Address set ThirdPartyAddressID='"+addID+"', FirstLineAddress='" + fAdd + "',County='" + county + " ', Postcode='" + post + "' where ThirdPartyAddressID='"+addID+"' ";
            
            stat = (PreparedStatement) connect.prepareStatement(q);
            
            stat.execute();
            
            JOptionPane.showMessageDialog(null, "Data Updated");
            
            stat.close();
            
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, ex);
        }
        
        updateAddressTable();
        clearAddress();
        } 

    }//GEN-LAST:event_updateButtonActionPerformed

    private void delAddButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_delAddButtonActionPerformed
        
        String message = " Are you sure want to delete the data?";
        String title = "Confirm";
        int reply = JOptionPane.showConfirmDialog(null, message, title, JOptionPane.YES_NO_OPTION);
        if (reply == JOptionPane.YES_OPTION) {
            
            try {
                
                String query = "delete from Address where ThirdPartyAddressID =?";
                
                stat = (PreparedStatement) connect.prepareStatement(query);
                stat.setString(1, addIDLabel.getText());
                stat.executeUpdate();
                JOptionPane.showMessageDialog(null, "Data deleted successfully");
                
                stat.close();
                
            } catch (Exception ex) {
                JOptionPane.showMessageDialog(null, ex);
            }
            
            updateAddressTable();
            clearAddress();
        }
        

    }//GEN-LAST:event_delAddButtonActionPerformed

    private void delAllAddButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_delAllAddButtonActionPerformed
        
        String message = " Are you sure want to delete the data?";
        String title = "Confirm";
        int reply = JOptionPane.showConfirmDialog(null, message, title, JOptionPane.YES_NO_OPTION);
        if (reply == JOptionPane.YES_OPTION) {
            
            try {
                
                String query = "delete from Address";
                
                stat = (PreparedStatement) connect.prepareStatement(query);
                
                stat.executeUpdate();
                JOptionPane.showMessageDialog(null, "Data deleted successfully");
                
                stat.close();
                
            } catch (Exception ex) {
                JOptionPane.showMessageDialog(null, ex);
            }
            
            updateAddressTable();
        }
        

    }//GEN-LAST:event_delAllAddButtonActionPerformed

    private void deleteButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteButtonActionPerformed
        
        String message = " Are you sure want to delete the data?";
        String title = "Confirm";
        int reply = JOptionPane.showConfirmDialog(null, message, title, JOptionPane.YES_NO_OPTION);
        if (reply == JOptionPane.YES_OPTION) {
            
            try {
                
                String query = "delete from ThirdPartySuppliers where thirdPartyID =?";
                
                stat = (PreparedStatement) connect.prepareStatement(query);
                stat.setString(1, tpsLabel.getText());
                stat.executeUpdate();
                JOptionPane.showMessageDialog(null, "Data deleted successfully");
                
                stat.close();
                
            } catch (Exception ex) {
                JOptionPane.showMessageDialog(null, ex);
            }
            
            updateTPS();
            clearTps();
        }
        

    }//GEN-LAST:event_deleteButtonActionPerformed

       /* To open the Gui form */ 
    
    private void orderButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_orderButtonActionPerformed
        ordersGui orders = new ordersGui();
        orders.setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_orderButtonActionPerformed

    private void trackButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_trackButtonActionPerformed
        trackGui track = new trackGui();
        track.setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_trackButtonActionPerformed

    private void repGUIButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_repGUIButtonActionPerformed
        newRepair rep = new newRepair();
        rep.setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_repGUIButtonActionPerformed

    private void listButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_listButtonActionPerformed
        summaryList list = new summaryList();
        list.setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_listButtonActionPerformed

    private void tpsMenuButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tpsMenuButtonActionPerformed
        thirdPartySuppliersGui tps = new thirdPartySuppliersGui();
        tps.setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_tpsMenuButtonActionPerformed

    private void parMenButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_parMenButtonActionPerformed
        partsGui part = new partsGui();
        part.setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_parMenButtonActionPerformed

    private void addIDTextFieldKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_addIDTextFieldKeyReleased
              try{
        String value = addIDTextField.getText();
        int click = Integer.parseInt(value);
        
        String query = "select * from Address where ThirdPartyAddressID='" + click + "' ";
        
        try {
            
            stat = (PreparedStatement) connect.prepareStatement(query);
            
            res = stat.executeQuery();
            
            if (res.next()) {
                
                String addAddressID = res.getString("ThirdPartyAddressID");
                addIDLabel.setText(addAddressID);
                String addAL1 = res.getString("FirstLineAddress");
                firstLineTextField.setText(addAL1);
                String addCounty = res.getString("County");
                countyTextField.setText(addCounty);
                String addPc = res.getString("Postcode");
                postcodeTextField.setText(addPc);
                
            }
            
            stat.close();
            res.close();
            
        } catch (Exception ex) {
            
            JOptionPane.showMessageDialog(null, "Enter Address ID");
        }
        }
        
        catch(NumberFormatException ex){
             JOptionPane.showMessageDialog(null, "Enter Address ID");
        }
    }//GEN-LAST:event_addIDTextFieldKeyReleased
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
        * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
        */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(thirdPartySuppliersGui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(thirdPartySuppliersGui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(thirdPartySuppliersGui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(thirdPartySuppliersGui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new thirdPartySuppliersGui().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addAddressButton;
    private javax.swing.JLabel addIDLabel;
    private javax.swing.JTextField addIDTextField;
    private javax.swing.JButton addTPSButton;
    private javax.swing.JTable addTable;
    private javax.swing.JButton clearAddressButton;
    private javax.swing.JButton clearTPSButton;
    private javax.swing.JTextField countyTextField;
    private javax.swing.JButton delAddButton;
    private javax.swing.JButton delAllAddButton;
    private javax.swing.JButton delAllButton;
    private javax.swing.JButton deleteButton;
    private javax.swing.JButton editButton;
    private javax.swing.JTextField firstLineTextField;
    private javax.swing.JTextField firstNameTextField;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextField lastNameTextField;
    private javax.swing.JButton listButton;
    private javax.swing.JPanel menuPanel;
    private javax.swing.JButton orderButton;
    private javax.swing.JButton parMenButton;
    private javax.swing.JTextField phoneTextField;
    private javax.swing.JFormattedTextField postcodeTextField;
    private javax.swing.JButton repGUIButton;
    private javax.swing.JPanel supPanel;
    private javax.swing.JTable tPartTable;
    private javax.swing.JLabel tpsLabel;
    private javax.swing.JButton tpsMenuButton;
    private javax.swing.JTable tpsTable;
    private javax.swing.JButton trackButton;
    private javax.swing.JButton updateButton;
    // End of variables declaration//GEN-END:variables
}
