/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vehiclemodule;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import net.proteanit.sql.DbUtils;

/**
 *
 * @author nathanwinslow
 */
public class Edit_RemoveStandardvehicle extends javax.swing.JFrame {
    Connection conn = null;
    ResultSet rs = null;
    PreparedStatement pst = null;
    /**
     * Creates new form Edit_RemoveStandardvehicle
     */
    public Edit_RemoveStandardvehicle() {
        initComponents();
        //comboBoxID();
        update_table();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        standard_vehicle = new javax.swing.JTable();
        stanVehicleID = new javax.swing.JTextField();
        make_field = new javax.swing.JTextField();
        model_field = new javax.swing.JTextField();
        engine_field = new javax.swing.JTextField();
        fuel_field = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        update_button = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        standard_vehicle.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        standard_vehicle.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                standard_vehicleMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(standard_vehicle);

        stanVehicleID.setText("Eg: \"1\"");
        stanVehicleID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                stanVehicleIDActionPerformed(evt);
            }
        });

        make_field.setText("eg: \"RENAULT\"");

        model_field.setText("eg: \"CLIO\"");

        engine_field.setText("eg: \"2.1\"");

        fuel_field.setText("eg: \"UNLEADED\"");

        jLabel1.setText("Standard Vehicle ID");

        jLabel2.setText("Vehicle Make");

        jLabel3.setText("Vehicle Model");

        jLabel4.setText("Vehicle Engine Size");

        jLabel5.setText("Vehicle Fuel Type");

        update_button.setText("Update");
        update_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                update_buttonActionPerformed(evt);
            }
        });

        jButton2.setText("Delete");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 585, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(48, 48, 48)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(update_button))
                        .addGap(102, 102, 102)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jButton2)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(fuel_field)
                                    .addComponent(engine_field)
                                    .addComponent(model_field)
                                    .addComponent(make_field)
                                    .addComponent(stanVehicleID, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(85, 85, 85)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(stanVehicleID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(make_field, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(model_field, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(engine_field, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fuel_field, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addGap(33, 33, 33)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(update_button)
                    .addComponent(jButton2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 44, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 23, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void stanVehicleIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_stanVehicleIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_stanVehicleIDActionPerformed

    private void update_table(){
        conn = javaConnect.connectDB();
        
       try{
        String sql = "Select * from standardVehicle";
        pst = conn.prepareStatement(sql);
        rs = pst.executeQuery();
        standard_vehicle.setModel(DbUtils.resultSetToTableModel(rs));
       
            pst.close();
            rs.close();
            conn.close();
       
       }
       catch(Exception e){
        JOptionPane.showMessageDialog(null, e);
           
       }
        
        
    }
    
    private void standard_vehicleMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_standard_vehicleMouseClicked
        conn = javaConnect.connectDB();
        
        
        try{
            int row = standard_vehicle.getSelectedRow();
            String Table_Choice = (standard_vehicle.getModel().getValueAt(row, 0).toString());
            
            String sql = "Select * from standardVehicle where stanVehicleID='"+Table_Choice+"' ";
            pst = conn.prepareStatement(sql);
            rs = pst.executeQuery();
            
           if(rs.next()){
               
               String take1 = rs.getString("stanVehicleID");
               stanVehicleID.setText(take1);
               String take2 = rs.getString("engineSize");
               engine_field.setText(take2);
               String take3 = rs.getString("make");
               make_field.setText(take3);
               String take4 = rs.getString("model");
               model_field.setText(take4);
               String take5 = rs.getString("fuelType");
               fuel_field.setText(take5);
               
               pst.close();
               rs.close();
               conn.close();
               
           }
        
        }
        catch(Exception e){
            // error message
                    JOptionPane.showMessageDialog(null, e);

        }
    }//GEN-LAST:event_standard_vehicleMouseClicked

    private void update_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_update_buttonActionPerformed
        conn = javaConnect.connectDB();
        
        try{
            String text1 = stanVehicleID.getText();
            String text2 = make_field.getText();
            String text3 = model_field.getText();
            String text4 = engine_field.getText();
            String text5 = fuel_field.getText();
            
            String sql = "update standardVehicle set make ='"+text2+"' ,model ='"+text3+"' ,fuelType='"+text5+"' ,engineSize = '"+text4+"' where stanVehicleID='"+text1+"' ";
            pst = conn.prepareStatement(sql);
            pst.execute();
            //System.out.println("Updated");
            update_table();
            
            pst.close();
            conn.close();
        }
        catch(Exception e){
            
            
        }
        
    }//GEN-LAST:event_update_buttonActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        conn = javaConnect.connectDB();
        int choice = JOptionPane.showConfirmDialog(null, "Are you sure you want to delete the row?", "Delete", JOptionPane.YES_NO_OPTION);
        
        if(choice == 0){
            try{
                String sql = "Delete from standardVehicle where stanVehicleID = ?";
                pst = conn.prepareStatement(sql);
                pst.setString(1, stanVehicleID.getText());
                pst.execute();
                    pst.close();
                    //rs.close();
                   conn.close();

                update_table();
            }
            catch(Exception e){
                        JOptionPane.showMessageDialog(null, e);


            }
        }
    }//GEN-LAST:event_jButton2ActionPerformed
//    private void comboBoxID(){
//        conn = javaConnect.connectDB();
//        try{
//           String sql = "select * from standardVehicle";
//           pst = conn.prepareStatement(sql);
//           rs = pst.executeQuery();
//           
//           while(rs.next()){
//               String stanVehicleID = rs.getString("stanVehicleID");
//               comboID.addItem(stanVehicleID);
//           }
//                pst.close();
//                rs.close();
//                conn.close();
//        }
//        catch(Exception e){
//            
//            
//        }
//    
//}
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Edit_RemoveStandardvehicle.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Edit_RemoveStandardvehicle.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Edit_RemoveStandardvehicle.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Edit_RemoveStandardvehicle.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Edit_RemoveStandardvehicle().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField engine_field;
    private javax.swing.JTextField fuel_field;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField make_field;
    private javax.swing.JTextField model_field;
    private javax.swing.JTextField stanVehicleID;
    private javax.swing.JTable standard_vehicle;
    private javax.swing.JButton update_button;
    // End of variables declaration//GEN-END:variables
}
