/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vehiclemodule;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import net.proteanit.sql.DbUtils;

/**
 *
 * @author nathanwinslow
 */
public class StandardVehicle extends javax.swing.JFrame {
Connection conn = null;
ResultSet rs = null;
PreparedStatement pst = null;

    /**
     * Creates new form StandardVehicle
     */
    public StandardVehicle() {
        initComponents();
        update_table1();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jTextField5 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        ASV_Table = new javax.swing.JTable();
        jPanel3 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        fuel_field = new javax.swing.JTextField();
        engine_field = new javax.swing.JTextField();
        model_field = new javax.swing.JTextField();
        make_field = new javax.swing.JTextField();
        stanVehicleID = new javax.swing.JTextField();
        update_button = new javax.swing.JButton();
        DeleteSV = new javax.swing.JButton();
        jPanel6 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        standard_vehicle = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        make_search = new javax.swing.JTextField();
        model_search = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTabbedPane1.setPreferredSize(new java.awt.Dimension(591, 568));
        jTabbedPane1.setRequestFocusEnabled(false);

        jPanel4.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jTextField2.setText("Make");
        jTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField2ActionPerformed(evt);
            }
        });

        jTextField3.setText("Model");

        jTextField4.setText("Fuel Type");

        jTextField5.setText("Engine Size");

        jButton1.setText("Add Standard Vehicle");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel1.setText("Make");

        jLabel2.setText("Model");

        jLabel3.setText("Fuel Type");

        jLabel4.setText("Engine Size");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addGap(55, 55, 55)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jTextField5)
                    .addComponent(jTextField4)
                    .addComponent(jTextField3)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(98, 98, 98))
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(181, 181, 181)
                .addComponent(jButton1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addGap(0, 17, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(18, 18, 18)
                .addComponent(jButton1))
        );

        jPanel7.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        ASV_Table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        )
        {public boolean isCellEditable(int row, int column){return false;}}
    );
    ASV_Table.addMouseListener(new java.awt.event.MouseAdapter() {
        public void mouseClicked(java.awt.event.MouseEvent evt) {
            ASV_TableMouseClicked(evt);
        }
    });
    jScrollPane1.setViewportView(ASV_Table);

    javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
    jPanel7.setLayout(jPanel7Layout);
    jPanel7Layout.setHorizontalGroup(
        jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(jPanel7Layout.createSequentialGroup()
            .addContainerGap()
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 542, Short.MAX_VALUE)
            .addContainerGap())
    );
    jPanel7Layout.setVerticalGroup(
        jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(jPanel7Layout.createSequentialGroup()
            .addContainerGap()
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 137, Short.MAX_VALUE)
            .addContainerGap())
    );

    javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
    jPanel2.setLayout(jPanel2Layout);
    jPanel2Layout.setHorizontalGroup(
        jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(jPanel2Layout.createSequentialGroup()
            .addContainerGap()
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addContainerGap())
    );
    jPanel2Layout.setVerticalGroup(
        jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(jPanel2Layout.createSequentialGroup()
            .addContainerGap()
            .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGap(80, 80, 80)
            .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addContainerGap(67, Short.MAX_VALUE))
    );

    jTabbedPane1.addTab("Add Standard Vehicle", jPanel2);

    jPanel5.setBorder(javax.swing.BorderFactory.createEtchedBorder());

    jLabel5.setText("Standard Vehicle ID");

    jLabel6.setText("Vehicle Make");

    jLabel7.setText("Vehicle Model");

    jLabel8.setText("Vehicle Engine Size");

    jLabel9.setText("Vehicle Fuel Type");

    fuel_field.setText("eg: \"UNLEADED\"");

    engine_field.setText("eg: \"2.1\"");

    model_field.setText("eg: \"CLIO\"");

    make_field.setText("eg: \"RENAULT\"");

    stanVehicleID.setEditable(false);
    stanVehicleID.setText("Eg: \"1\"");
    stanVehicleID.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            stanVehicleIDActionPerformed(evt);
        }
    });

    update_button.setText("Update");
    update_button.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            update_buttonActionPerformed(evt);
        }
    });

    DeleteSV.setText("Delete");
    DeleteSV.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            DeleteSVActionPerformed(evt);
        }
    });

    javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
    jPanel5.setLayout(jPanel5Layout);
    jPanel5Layout.setHorizontalGroup(
        jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(jPanel5Layout.createSequentialGroup()
            .addGap(19, 19, 19)
            .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jLabel7)
                .addComponent(jLabel5)
                .addComponent(jLabel6)
                .addComponent(jLabel8)
                .addComponent(jLabel9)
                .addComponent(update_button))
            .addGap(39, 39, 39)
            .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(DeleteSV)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(fuel_field)
                    .addComponent(engine_field)
                    .addComponent(model_field)
                    .addComponent(make_field)
                    .addComponent(stanVehicleID, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)))
            .addContainerGap(19, Short.MAX_VALUE))
    );
    jPanel5Layout.setVerticalGroup(
        jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(jPanel5Layout.createSequentialGroup()
            .addContainerGap()
            .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(stanVehicleID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(jLabel5))
            .addGap(18, 18, 18)
            .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(make_field, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(jLabel6))
            .addGap(18, 18, 18)
            .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(model_field, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(jLabel7))
            .addGap(18, 18, 18)
            .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(engine_field, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(jLabel8))
            .addGap(18, 18, 18)
            .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(fuel_field, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(jLabel9))
            .addGap(38, 38, 38)
            .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(update_button)
                .addComponent(DeleteSV))
            .addContainerGap(17, Short.MAX_VALUE))
    );

    jPanel6.setBorder(javax.swing.BorderFactory.createEtchedBorder());

    standard_vehicle.setModel(new javax.swing.table.DefaultTableModel(
        new Object [][] {
            {null, null, null, null},
            {null, null, null, null},
            {null, null, null, null},
            {null, null, null, null}
        },
        new String [] {
            "Title 1", "Title 2", "Title 3", "Title 4"
        }
    )
    {public boolean isCellEditable(int row, int column){return false;}}
    );
    standard_vehicle.addMouseListener(new java.awt.event.MouseAdapter() {
        public void mouseClicked(java.awt.event.MouseEvent evt) {
            standard_vehicleMouseClicked(evt);
        }
    });
    jScrollPane2.setViewportView(standard_vehicle);

    javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
    jPanel6.setLayout(jPanel6Layout);
    jPanel6Layout.setHorizontalGroup(
        jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(jPanel6Layout.createSequentialGroup()
            .addContainerGap()
            .addComponent(jScrollPane2)
            .addContainerGap())
    );
    jPanel6Layout.setVerticalGroup(
        jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(jPanel6Layout.createSequentialGroup()
            .addContainerGap()
            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 141, Short.MAX_VALUE)
            .addContainerGap())
    );

    jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

    jLabel10.setText("Make");

    jLabel11.setText("Model");

    make_search.addKeyListener(new java.awt.event.KeyAdapter() {
        public void keyReleased(java.awt.event.KeyEvent evt) {
            make_searchKeyReleased(evt);
        }
    });

    model_search.addKeyListener(new java.awt.event.KeyAdapter() {
        public void keyReleased(java.awt.event.KeyEvent evt) {
            model_searchKeyReleased(evt);
        }
    });

    jLabel12.setText("Search");

    javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
    jPanel1.setLayout(jPanel1Layout);
    jPanel1Layout.setHorizontalGroup(
        jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(jPanel1Layout.createSequentialGroup()
            .addContainerGap()
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addComponent(jLabel11)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 35, Short.MAX_VALUE)
                    .addComponent(model_search, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                    .addComponent(jLabel10)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel12)
                        .addComponent(make_search, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))))
            .addGap(30, 30, 30))
    );
    jPanel1Layout.setVerticalGroup(
        jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
            .addContainerGap()
            .addComponent(jLabel12)
            .addGap(14, 14, 14)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(jLabel10)
                .addComponent(make_search, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGap(18, 18, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(jLabel11)
                .addComponent(model_search, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGap(10, 10, 10))
    );

    jButton3.setText("Revert");
    jButton3.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            jButton3ActionPerformed(evt);
        }
    });

    javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
    jPanel3.setLayout(jPanel3Layout);
    jPanel3Layout.setHorizontalGroup(
        jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(jPanel3Layout.createSequentialGroup()
            .addContainerGap()
            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createSequentialGroup()
                    .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                            .addGap(0, 0, Short.MAX_VALUE)
                            .addComponent(jButton3)))))
            .addContainerGap())
    );
    jPanel3Layout.setVerticalGroup(
        jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(jPanel3Layout.createSequentialGroup()
            .addGap(29, 29, 29)
            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                .addGroup(jPanel3Layout.createSequentialGroup()
                    .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(24, 24, 24))
                .addGroup(jPanel3Layout.createSequentialGroup()
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton3)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
            .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addContainerGap())
    );

    jTabbedPane1.addTab("Edit/Update Standard Vehicle", jPanel3);

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
    getContentPane().setLayout(layout);
    layout.setHorizontalGroup(
        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(layout.createSequentialGroup()
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGap(0, 0, Short.MAX_VALUE))
    );
    layout.setVerticalGroup(
        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(layout.createSequentialGroup()
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGap(0, 0, Short.MAX_VALUE))
    );

    pack();
    }// </editor-fold>//GEN-END:initComponents
    
    
    private void update_table1(){
        conn = javaConnect.connectDB();
        
       try{
        String sql = "Select * from standardVehicle";
        pst = conn.prepareStatement(sql);
        rs = pst.executeQuery();
        ASV_Table.setModel(DbUtils.resultSetToTableModel(rs));
        
            
       
       
       }
       catch(Exception e){
        JOptionPane.showMessageDialog(null, e);
           
       }
       
       try{
        String sql = "Select * from standardVehicle";
        pst = conn.prepareStatement(sql);
        rs = pst.executeQuery();
        standard_vehicle.setModel(DbUtils.resultSetToTableModel(rs));
       
       }
       catch(Exception e){
        JOptionPane.showMessageDialog(null, e);
           
       }
       finally{
           try {
               pst.close();
               rs.close();
               conn.close();
           } catch (SQLException ex) {
              
           }
        }  
     }
    
    
    private void jTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField2ActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_jTextField2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        System.out.println("Test");   
        conn = javaConnect.connectDB();
           boolean doubleTest = false;
        try{
            System.out.println("Test2");
//            StandardV sv = new StandardV();
            System.out.println("test3");
            
            
           String sql = "insert into standardVehicle (engineSize,make,model,fuelType) values(UPPER(?),UPPER(?),UPPER(?),UPPER(?))";
            pst = conn.prepareStatement(sql);
            
            int test1 = jTextField5.getText().length();
            int test2 = jTextField2.getText().length();
            int test3 = jTextField3.getText().length();
            int test4 = jTextField4.getText().length();
            
            try {
                    String text4 = jTextField5.getText();
                    Double.parseDouble(text4);
                    doubleTest = true;
                    
                } 
                catch (NumberFormatException e) {
                    doubleTest = false;
                }
            
            if(test1 == 0 || test2 == 0 || test3 == 0 || test4 == 0){
                    JOptionPane.showMessageDialog(null,"Text fields can not be empty"); 
                    conn.close();
                }
            if(test1 > 20 || test2 > 20|| test3 > 20 || test4 > 20){
                    JOptionPane.showMessageDialog(null,"Text Fields can not be to long");
                    conn.close();
                }
             if(doubleTest == false){
                    JOptionPane.showMessageDialog(null,"Engine size must be a number eg: 1.0");
                    conn.close();
                }
            
            
            pst.setString(1,jTextField5.getText());
            pst.setString(2,jTextField2.getText());
            pst.setString(3,jTextField3.getText());
            pst.setString(4,jTextField4.getText());

            pst.execute();
            
            update_table1();
                
        }
        catch(Exception e){
            System.out.println(e);
        }
        finally{
           try {
               pst.close();
               rs.close();
               conn.close();
           } catch (SQLException ex) {
              
           }
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void stanVehicleIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_stanVehicleIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_stanVehicleIDActionPerformed

    private void update_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_update_buttonActionPerformed
       conn = javaConnect.connectDB();
       boolean doubleTest = false;
       int choice = JOptionPane.showConfirmDialog(null, "Are you sure you want to Update the row?", "Update", JOptionPane.YES_NO_OPTION);
        if(choice == 0){
            try{
                
                
                int test1 = stanVehicleID.getText().length();
                int test2 = make_field.getText().length();
                int test3 = model_field.getText().length();
                int test4 = engine_field.getText().length();
                int test5 = fuel_field.getText().length();
                
                try {
                    String text4 = engine_field.getText();
                    Double.parseDouble(text4);
                    doubleTest = true;
                    System.out.println("test" + doubleTest);
                } 
                catch (NumberFormatException e) {
                    doubleTest = false;
                    System.out.println("test2" + doubleTest);
                
                }
                
                
                if(test1 == 0 || test2 == 0 || test3 == 0 || test5 == 0 || test4 == 0){
                    JOptionPane.showMessageDialog(null,"Text fields can not be empty"); 
                    conn.close();
                }
                if(test1 > 30 || test2 > 30|| test3 > 30 || test5 > 30){
                    JOptionPane.showMessageDialog(null,"Text Fields can not be to long");
                    conn.close();
                }
                if(doubleTest == false){
                    JOptionPane.showMessageDialog(null,"Engine size must be a number eg: 1.0");
                    conn.close();
                }
                
                String take1 = stanVehicleID.getText();
                String take2 = make_field.getText();
                String take3 = model_field.getText();
                String take4 = engine_field.getText();
                String take5 = fuel_field.getText();
                
                
                
                String sql = "update standardVehicle set make ='"+take2+"' ,model ='"+take3+"' ,"
                        + "fuelType ='"+take5+"' ,engineSize ='"+take4+"' where stanVehicleID ='"+take1+"' ";
                        pst = conn.prepareStatement(sql);
                        pst.execute();
                        
                        pst.close();
                       //rs.close();
                       conn.close();
                        
                        update_table1();
                        
                }
            catch(Exception e){
                
            }
        }
        
    }//GEN-LAST:event_update_buttonActionPerformed

    private void DeleteSVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DeleteSVActionPerformed
        conn = javaConnect.connectDB();
        int choice = JOptionPane.showConfirmDialog(null, "Are you sure you want to delete the row?", "Delete", JOptionPane.YES_NO_OPTION);

        if(choice == 0){
            try{
                String sql = "Delete from standardVehicle where stanVehicleID = ?";
                pst = conn.prepareStatement(sql);
                pst.setString(1, stanVehicleID.getText());
                pst.execute();
                

                update_table1();
            }
            catch(Exception e){
                JOptionPane.showMessageDialog(null, e);

            }
            finally{
           try {
               pst.close();
               //rs.close();
               conn.close();
           } catch (SQLException ex) {
              
           }
        }
        }
    }//GEN-LAST:event_DeleteSVActionPerformed

    private void standard_vehicleMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_standard_vehicleMouseClicked
        conn = javaConnect.connectDB();

        try{
            int row = standard_vehicle.getSelectedRow();
            String Table_Choice = (standard_vehicle.getModel().getValueAt(row, 0).toString());

            String sql = "Select * from standardVehicle where stanVehicleID='"+Table_Choice+"' ";
            pst = conn.prepareStatement(sql);
            rs = pst.executeQuery();

            if(rs.next()){

                String take1 = rs.getString("stanVehicleID");
                stanVehicleID.setText(take1);
                String take2 = rs.getString("engineSize");
                engine_field.setText(take2);
                String take3 = rs.getString("make");
                make_field.setText(take3);
                String take4 = rs.getString("model");
                model_field.setText(take4);
                String take5 = rs.getString("fuelType");
                fuel_field.setText(take5);
                
                
               pst.close();
               
               rs.close();
               
               conn.close();
               
               
                update_table1();

            }

        }
        catch(Exception e){
            // error message
            JOptionPane.showMessageDialog(null, e);

        }
        
    }//GEN-LAST:event_standard_vehicleMouseClicked

    private void ASV_TableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ASV_TableMouseClicked
            conn = javaConnect.connectDB();

        try{
            int row = ASV_Table.getSelectedRow();
            String Table_Choice = (ASV_Table.getModel().getValueAt(row, 0).toString());

            String sql = "Select * from standardVehicle where stanVehicleID='"+Table_Choice+"' ";
            pst = conn.prepareStatement(sql);
            rs = pst.executeQuery();

            if(rs.next()){

//                String take1 = rs.getString("stanVehicleID");
//                stanVehicleID.setText(take1);
                String take2 = rs.getString("engineSize");
                jTextField5.setText(take2);
                String take3 = rs.getString("make");
                jTextField2.setText(take3);
                String take4 = rs.getString("model");
                jTextField3.setText(take4);
                String take5 = rs.getString("fuelType");
                jTextField4.setText(take5);

               
               pst.close();
            
               rs.close();
               
               conn.close();
               
                
                update_table1();

            }

        }
        catch(Exception e){
            // error message
            JOptionPane.showMessageDialog(null, e);

        }
        
    }//GEN-LAST:event_ASV_TableMouseClicked

    private void make_searchKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_make_searchKeyReleased
        conn = javaConnect.connectDB();

        try{
            String sql = "select stanVehicleID,make,model from standardVehicle where make =?";
            pst = conn.prepareStatement(sql);
            pst.setString(1, make_search.getText().toUpperCase());
            
            rs = pst.executeQuery();
            
            standard_vehicle.setModel(DbUtils.resultSetToTableModel(rs));
            
            
        }
        catch(Exception e){
        }
        finally{
           try {
               pst.close();
               rs.close();
               conn.close();
               
           } catch (SQLException ex) {
              
           }
        }
    }//GEN-LAST:event_make_searchKeyReleased

    private void model_searchKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_model_searchKeyReleased
        conn = javaConnect.connectDB();

        try{
            String sql = "select stanVehicleID,make,model from standardVehicle where model =?";
            pst = conn.prepareStatement(sql);
            pst.setString(1, model_search.getText().toUpperCase());
            
            rs = pst.executeQuery();
            
            standard_vehicle.setModel(DbUtils.resultSetToTableModel(rs));
            
            
        }
        catch(Exception e){
            
        }
        finally{
           try {
               pst.close();
               rs.close();
               conn.close();
           } catch (SQLException ex) {
              
           }
        }
    }//GEN-LAST:event_model_searchKeyReleased

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        update_table1();
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(StandardVehicle.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(StandardVehicle.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(StandardVehicle.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(StandardVehicle.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new StandardVehicle().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable ASV_Table;
    private javax.swing.JButton DeleteSV;
    private javax.swing.JTextField engine_field;
    private javax.swing.JTextField fuel_field;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField make_field;
    private javax.swing.JTextField make_search;
    private javax.swing.JTextField model_field;
    private javax.swing.JTextField model_search;
    private javax.swing.JTextField stanVehicleID;
    private javax.swing.JTable standard_vehicle;
    private javax.swing.JButton update_button;
    // End of variables declaration//GEN-END:variables
}
